# Generated by Django 4.1.3 on 2022-12-05 13:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary_info', '0001_initial'),
        ('students', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief', models.BooleanField(default=False, verbose_name='Is chief cook')),
            ],
            options={
                'verbose_name': 'cook',
                'verbose_name_plural': 'cooks',
                'db_table': 'cook',
            },
        ),
        migrations.CreateModel(
            name='WorkerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Worker List', max_length=255, verbose_name='Title of worker list')),
                ('token', models.CharField(blank=True, max_length=40, null=True, verbose_name='Access token to worker list')),
                ('token_expiration_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 18, 48, 43, 227865), verbose_name='Expiration date of token')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'worker list',
                'verbose_name_plural': 'worker lists',
                'db_table': 'worker_list',
            },
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_courses', models.PositiveSmallIntegerField(default=0, verbose_name='Number of advanced training courses completed')),
                ('has_classroom', models.BooleanField(default=False, verbose_name='Teacher has classroom')),
                ('subjects', models.ManyToManyField(to='students.subject', verbose_name='Subjects')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Date of first creating')),
                ('job_title', models.CharField(choices=[('ordinary_worker', 'ordinary worker'), ('teacher', 'teacher'), ('cook', 'cook')], max_length=50, verbose_name='Job title')),
                ('status', models.CharField(choices=[('active', 'active'), ('time_off', 'time off'), ('vacation', 'vacation'), ('overtime', 'overtime'), ('sick', 'sick'), ('decree', 'decree')], default='active', max_length=50, verbose_name='Working status')),
                ('months_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Number of months of experience')),
                ('wage_rate', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='The rate for which the employee works')),
                ('wage_rate_salary', models.PositiveIntegerField(default=6000, verbose_name='Salary for one job')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Id of extension type. E.g. id of `TeacherType`')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Worker extension. Like a teacher or a cook. Leave blank if this is a regular employee')),
                ('salary_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salary_info.workersalaryinfo', verbose_name='Model with fields for salary calculation')),
                ('worker_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.workerlist', verbose_name='Worker list')),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'workers',
                'db_table': 'worker',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
