# Generated by Django 4.1.3 on 2022-12-07 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 7, 16, 48, 1, 470851), verbose_name='Expiration date of token'),
        ),
    ]
