# Generated by Django 4.1.4 on 2022-12-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='owners',
            field=models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='owners'),
        ),
    ]
