# Generated by Django 4.1.3 on 2022-12-05 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_workerlist_token_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='job_title',
            field=models.CharField(max_length=255, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='workerlist',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 19, 28, 16, 729421), verbose_name='Expiration date of token'),
        ),
    ]
