# Generated by Django 4.1.3 on 2022-12-05 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlist',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 19, 20, 16, 848785), verbose_name='Expiration date of token'),
        ),
    ]
