# Generated by Django 4.1.3 on 2022-12-07 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_workerlist_token_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='workers.workerlist', verbose_name='Worker list'),
        ),
        migrations.AlterField(
            model_name='workerlist',
            name='token_expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 7, 22, 39, 36, 770790), verbose_name='Expiration date of token'),
        ),
    ]
